### ISSUE TITLE
Bug downloading the dataset

### ISSUE THREAD

**Issue by thorongil05** [terrierteam/pyterrier_colbert#17]
```python
import pyterrier as pt
import faiss
from pyterrier_colbert.indexing import ColBERTIndexer

if not pt.started(): pt.init()

dataset = pt.get_dataset('vaswani')
print("Files in vaswani corpus: %s " % dataset.get_corpus())
```
This code raises the following error: 'NoneType' object is not callable.

I noticed that the problem is caused by the importing of ColBERTIndexer. Indeed, the snippet works just moving this line in the bottom.

```python
import pyterrier as pt
import faiss

if not pt.started(): pt.init()

dataset = pt.get_dataset('vaswani')
print("Files in vaswani corpus: %s " % dataset.get_corpus())

from pyterrier_colbert.indexing import ColBERTIndexer
```

**Comment by cmacdonald** [comment]
OK. Is there somewhere you saw this code snippet, that we should update?

**Comment by seanmacavaney** [comment]
It doesn't seem ideal that `pt.get_dataset()` would break in this way when `pyterrier_colbert` is imported before pt is started though. (And it's unclear to me why it even breaks on `get_dataset`, given the import of `pyterrier_colbert` works just fine.)

Maybe a test at the top of `__init__.py` we check that `pt.started()` and if not, raise an error telling the user they must init pt first?

**Comment by cmacdonald** [comment]
Antonio, Sean says exactly what we need

>Maybe a test at the top of __init__.py we check that pt.started() and if not, raise an error telling the user they must init pt first?

For test, it should be assert.

**Comment by thorongil05** [comment]
Ok, I will add it ASAP.

**Comment by cmacdonald** [comment]
Now addressed
