### ISSUE TITLE
Data Format when indexing 

### ISSUE THREAD

**Issue by puzzlecollector** [terrierteam/pyterrier_colbert#22]
@cmacdonald  
When trying to index my custom dataset with a trained ColBERT checkpoint, what should the dataset format be like? My corpus is a pandas dataframe organized as follows 

![image](https://user-images.githubusercontent.com/15623464/140867703-a4919fe4-af5e-4b34-b9ba-7f4ba84f049b.png)

and I am using the following code to declare the indexer and as well as to index 
```
indexer = pyterrier_colbert.indexing.ColBERTIndexer(checkpoint, "colbert_content", "colbertindex", chunksize=3) 

indexer.index(corpus)
```

But if I simply run this code (with corpus being the pandas dataframe that looks like the screenshot above) I get an error. 

How should I organize my corpus data (the data that I want to search) in order to properly index them?

**Comment by cmacdonald** [comment]
Hi Luke

Nice question. 

Its meant to be like [IterDictIndexer](https://pyterrier.readthedocs.io/en/latest/terrier-indexing.html#pyterrier.IterDictIndexer) rather than [DFIndexer](https://pyterrier.readthedocs.io/en/latest/terrier-indexing.html#dfindexer).

To pass a DataFrame to it, use `indexer.index(df.to_dict(orient="records"))`

**Comment by puzzlecollector** [comment]
@cmacdonald Thanks! will try and let you know if there are any issues :)

**Comment by wpertsch** [comment]
Hello @puzzlecollector, Hello @cmacdonald,
I hope this is not off-topic, but is there a way to index normal Trec-files with this ColbertIndexer or do I have to make a dict?

**Comment by cmacdonald** [comment]
You have to make a dict. There is however an (undocumented? *) helper function for this in PyTerrier  - see https://github.com/terrier-org/pyterrier/blob/master/pyterrier/index.py#L125

*: PRs gratefully received ;-)

**Comment by wpertsch** [comment]
Ok thanks, this worked!
This was my Solution:
```python
checkpoint="http://www.dcs.gla.ac.uk/~craigm/colbert.dnn.zip"
from pyterrier_colbert.indexing import ColBERTIndexer
indexer = ColBERTIndexer(checkpoint, "/content", "colbert_index", chunksize=3)
files = pt.io.find_files("/content/Data")
gen = pt.index.treccollection2textgen(files)
indexer.index(gen)
```

**Comment by cmacdonald** [comment]
Yes. I have added documentation about both of these hints to the terrier-indexing.rst, which should appear one readthedocs builds are fixed. Closing this issue now.

Craig
