### ISSUE TITLE
No faiss index found

### ISSUE THREAD

**Issue by wpertsch** [terrierteam/pyterrier_colbert#23]
When rebuilding the [vaswani.ipynb-Experiment](https://colab.research.google.com/github/cmacdonald/pyterrier_colbert/blob/main/vaswani.ipynb) with my own index, the retrieval was not possible because `ivfpq.faiss` was expected, but `ivfpq.100.faiss` was build. After renaming this, everything worked as expected.

The Indexing: 
```python
checkpoint="http://www.dcs.gla.ac.uk/~craigm/colbert.dnn.zip"
from pyterrier_colbert.indexing import ColBERTIndexer
indexer = ColBERTIndexer(checkpoint, "/content", "colbert_index", chunksize=3)
files = pt.io.find_files("/content/Data")
gen = pt.index.treccollection2textgen(files)
indexer.index(gen)
```

The Retrieval:
```python
from pyterrier_colbert.ranking import ColBERTFactory
import pyterrier_colbert.indexing
pyterrier_colbert_factory = pyterrier_colbert.ranking.ColBERTFactory(checkpoint, "/content", "colbert_index")
colbert_e2e = pyterrier_colbert_factory.end_to_end()
(colbert_e2e % 10).search("chemical reactions")
```

Is there an Error in my code, or is this a bug?
Kind Regards,
Wilhelm

**Comment by cmacdonald** [comment]
its a known bug. Colbert does some auto calculation of faiss num_partitions if its not set at indexing time. However, we dont record it properly when reopening the factory object.

**Comment by wpertsch** [comment]
Ok thank you for the quick response.

**Comment by cmacdonald** [comment]
I think fixing would require some fixing upstream in ColBERT, and its not a humungous problem to rename/symlink.
