### ISSUE TITLE
Number of epochs to train the Colbert model in the fit( )

### ISSUE THREAD

**Issue by poorya2021** [terrierteam/pyterrier_colbert#37]
Hi everyone
I had a question about training the Colbert model

How can I change the epoch and batch size for the ```fit( )``` function used to train the model?

What is the number of default epochs in the ```fit( )``` function?

Which part can I see the settings for the number of epochs and batch sizes for the ```fit( )``` function?

Thank you

**Comment by cmacdonald** [comment]
pyterrier_colbert doesnt expose a fit function. The ColBERT documentation on training applies.

**Comment by poorya2021** [comment]
> 
Then
Is there no function or method for training Pyterrier_ColBERT?

**Comment by cmacdonald** [comment]
The model that we provide in our notebooks is trained on MSMARCO passage ranking, and works effectively on many other corpora in a zero-shot fashion. To build that model, we followed the training instructions at https://github.com/stanford-futuredata/ColBERT#training and trained for 44,500 steps.

Training as part of a PyTerrier pipeline would be more expensive, as ranking would need to be performed, etc.

**Comment by poorya2021** [comment]
Ok thank you
