### ISSUE TITLE
pyterrier_colbert installation

### ISSUE THREAD

**Issue by sundavid2002** [terrierteam/pyterrier_colbert#43]
I was trying to implement pyterrier_colbert's indexes using Visual Studio Code. When I tried to install pyterrier_colbert from GitHub, using "pip install --upgrade git+https://github.com/terrierteam/pyterrier_colbert.git", I got the error messages"ERROR: Failed building wheel for tokenizers, & "ERROR: Could not build wheels for tokenizers, which is required to install pyproject.toml-based projects". What can this be fixed?

**Comment by seanmacavaney** [comment]
`tokenizers` is a package from HuggingFace's `transformers`. Do you get the same error if you:
```bash
pip install --upgrade transformers==2.1.1
```
?

**Comment by sundavid2002** [comment]
Yes

**Comment by sundavid2002** [comment]
When I try "pip install --upgrade transformers==2.1.1", that command works w/o any errors, but when I try "pip install --upgrade git+https://github.com/terrierteam/pyterrier_colbert.git", that command returns same errors as before

**Comment by sundavid2002** [comment]
Do you suggest I execute "pip install --upgrade transformers==2.1.1" instead of "pip install --upgrade git+https://github.com/terrierteam/pyterrier_colbert.git" or before "pip install --upgrade git+https://github.com/terrierteam/pyterrier_colbert.git"?

**Comment by seanmacavaney** [comment]
Oops, I was looking at the wrong branch. Can you try `pip install --upgrade transformers==3.0.2` on its own?

The thing is that the error message suggests that it originates from HuggingFace `tokenizers`, so the first step in debugging it is to isolate the problem.

**Comment by cmacdonald** [comment]
@sundavid2002 did you get to the bottom of this. I think pyt_colbert supports transformers 4, and I removed the dependency on the specific transformers version from our forked colbert repo.

**Comment by cmacdonald** [comment]
No update.
