### ISSUE TITLE
Does this support ColBERTv2?

### ISSUE THREAD

**Issue by JohnGiorgi** [terrierteam/pyterrier_colbert#47]
Wondering if this would support ColBERT v2? E.g. by installing the main branch of [ColBERT](https://github.com/stanford-futuredata/ColBERT/) and providing a ColBERTv2 checkpoint to `pyterrier_colbert`?

**Comment by cmacdonald** [comment]
Our [fork](https://github.com/cmacdonald/colbert/tree/v0.2) of ColBERT has diverged a bit, in part due to changes upstream, and also to support functionality here. Is there something specific from ColBERT v2 that you need?
 
We'd happily look at a PR that brought things back into line, but its not something we can cycles to work on ourselves.

**Comment by JohnGiorgi** [comment]
Nothing in particular! Was just looking for a good re-ranker to use with PyTerrier but I realized I can use `pt.apply_doc_score` for this purpose!

https://pyterrier.readthedocs.io/en/latest/apply.html#pyterrier.apply.doc_score

**Comment by cmacdonald** [comment]
>  looking for a good re-ranker to use with PyTerrier

See also the [T5 repo](https://github.com/terrierteam/pyterrier_t5).

**Comment by JohnGiorgi** [comment]
Awesome thanks, will take a look.

**Comment by wpertsch** [comment]
When just using basic functions of pyterrier_colbert, can I use colbert v0.2 checkpoints or does it just work with colbert v0.1 ones?

**Comment by wpertsch** [comment]
The created/trained ColBERTv0.2 checkpoints are generated in the form of folders with the files
```
artifact.metadata  config.json  pytorch_model.bin  special_tokens_map.json  tokenizer_config.json  tokenizer.json  vocab.txt
```
inside them.
Also, the [pretrained checkpoint](https://github.com/stanford-futuredata/ColBERT#overview) is presented like this. I assume that pyterrier_colbert needs a 'checkpoint.dnn' file. Any clues on how this is obtainable from the v0.2 checkpoints?

**Comment by cmacdonald** [comment]
I think thats a BERT pre-trained model. ColBERT v0.2 creates .dnn files. See https://github.com/cmacdonald/ColBERT/blob/v0.2/colbert/training/utils.py#L28
Specifically, these are named colbert-STEPS.dnn and created, by default, for the following steps:
https://github.com/cmacdonald/ColBERT/blob/v0.2/colbert/parameters.py#L9


Make sure you are looking in the right place? Worth using the unix find command and grepping for .dnn files
