### ISSUE TITLE
Unable to extract query/object scores.

### ISSUE THREAD

**Issue by zhaozhengyu0328** [terrierteam/pyterrier_colbert#53]
Hello,

I recently used your code for colbert retrieval  

res = (0.8* colbert_e2e_base+0.2*colbert_e2e).transform(topic)
pt.Experiment(
    [res1],
    topic.head(50),
    #dataset.get_topics().head(50),
    dataset.get_qrels(),
    eval_metrics = ["map", "recip_rank", "mrt", "P_10", "P_20", "ndcg_cut_20"],
    names = ["ColBERT_ours"]
)

I meet this problem

TypeError: Unable to extract query/object scores.
I tried to use the Pytrec_eval native method, but I got the following problem, what is the problem probably?
![image](https://user-images.githubusercontent.com/52226743/192729853-a7ebc993-6233-4cde-995c-a8297043059e.png)

Thank you very much for your time!

**Comment by cmacdonald** [comment]
Can tell us the output of `res.dtypes`? 

Also 
```python
pt.Experiment(
[(0.8* colbert_e2e_base+0.2*colbert_e2e)],
topic.head(50),
#dataset.get_topics().head(50),
dataset.get_qrels(),
eval_metrics = ["map", "recip_rank", "mrt", "P_10", "P_20", "ndcg_cut_20"],
names = ["ColBERT_ours"]
)
``` 

should work too.

**Comment by cmacdonald** [comment]
And what is your pytrec_eval version?  Are you using a recent version of Pyterrier? Tracing the likely code, I expect there to be another error message.

**Comment by cmacdonald** [comment]
Finally, I note that in
```
res = (0.8* colbert_e2e_base+0.2*colbert_e2e).transform(topic)
pt.Experiment(
[res1],
topic.head(50),
#dataset.get_topics().head(50),
dataset.get_qrels(),
eval_metrics = ["map", "recip_rank", "mrt", "P_10", "P_20", "ndcg_cut_20"],
names = ["ColBERT_ours"]
)
```
You have  `topic.head(50)` in the pt.Experiment, but `res` is generated from only a single topic. This looks a bit odd to me.

**Comment by zhaozhengyu0328** [comment]
thanks for your answer , I find the error in my work , the type of docno in my dataset is float, but the type of docno in pyterier is object, i use dataframe.astype(object), after this ,some scores in the result is nan,so i can't extract query/object scores.

the code i push firstly is error because the network error i can't edit it .

**Comment by cmacdonald** [comment]
Could you share the code of colbert_e2e_base or colbert_e2e - I'm wondering if we need to force the dtype in some of the pyt_colbert code?

**Comment by zhaozhengyu0328** [comment]
ok, i run the code and get the type of my data
res1(colbert_e2e_base):
![XGNOFY0C8WA_`~}S`S0PQFU](https://user-images.githubusercontent.com/52226743/192795006-ee96ab96-c033-4a7b-9150-09e1beec1b9d.png)
res2(colbert_e2e):
![_F@SO(H8U{NIDMLNV{SH9FL](https://user-images.githubusercontent.com/52226743/192794991-e2193880-9a4f-4000-9f3b-d1e1a66a8ea0.png)    here i use .astype to transform my float to object , finally i get the result
