### ISSUE TITLE
Indexing dataset read using `pt.io.find_files`

### ISSUE THREAD

**Issue by carsonwoods** [terrierteam/pyterrier_colbert#68]
Is there a recommended way to build an index on a corpus that isn't provided via a PyTerrier dataset? The example code provided shows that this is an appropriate way to build an index:

```python
from pyterrier_colbert.indexing import ColBERTIndexer
indexer = ColBERTIndexer("/path/to/checkpoint.dnn", "/path/to/index", "index_name")
indexer.index(dataset.get_corpus_iter())
```

This code relies on the `dataset.get_corpus_iter()` function. The dataset I'm working with is a TREC collection which (when only using PyTerrier), I have indexed using the following approach:

```python
news_corpus_files = pt.io.find_files("/content/news_corpus/text")

indexer = pt.TRECCollectionIndexer(
    "/content/news_index",
    meta={"docno": 26, "text": 4096},
    meta_tags={"text": "ELSE"},
    verbose=True,
)

indexer.index(news_corpus_files)
```
Is there a similar way to use the `ColBERTIndexer` using a dataset that was read using `pt.io.find_files()`?

Thanks in advance for any help with this issue!

**Comment by cmacdonald** [comment]
Hi Carson. Thanks for the nice question.

ColBERTIndexer abides by the pt.Indexer API, so anything* you can make into an iterable of dictionaries can be indexed. 
e.g.
```python
indexer.index([{'docno' : 'd1', 'text' : 'hello there'}])
```
Indeed, `dataset.get_corpus_iter()` just returns a Python generator of dictionaries.

*: ColBERT gets unhappy with small indices, I think its like 200 docs minimum.

**Comment by carsonwoods** [comment]
Hi Craig, that makes sense. Thanks for the quick reply and the help! I'll go ahead and close this issue for now. 

Thanks again!
